### ISSUE TITLE
Django Modal window issues

### ISSUE THREAD

**Issue by bioscom** [morlandi/django-frontend-forms#25]
I just got on python Django developing a blog. I want to use popup modal view in my application, I googled and I came across the link below;
https://brainstorm.it/snippets/ajax-form-submission-django/

I implemented it, and when I clicked the link button it actually enters the view.py functional view, but it does not popup the page.
I don't know where I'm getting it wrong. I will appreciate if I can get a download of a sample application where this is implemented.

Thank you very much.

**Comment by morlandi** [comment]
Hello @bioscom ,
you can download the whole repo and you'll find a sample Django project in the `example` subfolder.

It's more a list of (incomplete) documents for sharing techniques and best practices, but here and there you can find some working examples, for example here:

http://127.0.0.1:8000/samples/form-submission/

**Comment by bioscom** [comment]
Thank you very much for your quick response. But 127.0.0.1 is my localhost, I can't use that to get I to your machine to download the files.

You can help put in a GitHub and send the link.

Thanks.

Isaac Bejide

**Comment by bioscom** [comment]
Thanks. 

I have seen it here  https://github.com/morlandi/django-frontend-forms

Thank you very much

**Comment by morlandi** [comment]
You should run the Django example project locally with `python manage.py runserver`, then visit http://127.0.0.1:8000
